/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import codes.Kitchen;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lennon
 */
public class Forno extends javax.swing.JFrame {
    codes.Kitchen cozinha = new codes.Kitchen();
    codes.Exceptions exc =  new codes.Exceptions();
    /**
     * Creates new form Forno
     */
    public Forno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldInTemp = new javax.swing.JTextField();
        jTextFieldInTime = new javax.swing.JTextField();
        jTextFieldOutTemp = new javax.swing.JTextField();
        jTextFieldOutTime = new javax.swing.JTextField();
        jButtonStart = new javax.swing.JButton();
        jButtonZero = new javax.swing.JButton();

        setTitle("FORNO ELETRICO");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TEMPERATURA");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TIMER");

        jTextFieldInTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInTempActionPerformed(evt);
            }
        });

        jTextFieldInTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInTimeActionPerformed(evt);
            }
        });

        jTextFieldOutTemp.setEditable(false);
        jTextFieldOutTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOutTempActionPerformed(evt);
            }
        });

        jTextFieldOutTime.setEditable(false);
        jTextFieldOutTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOutTimeActionPerformed(evt);
            }
        });

        jButtonStart.setText("COMEÇAR");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jButtonZero.setText("ZERAR");
        jButtonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldInTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldInTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldOutTime)
                            .addComponent(jTextFieldOutTemp)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonZero)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldInTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldOutTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldInTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldOutTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStart)
                    .addComponent(jButtonZero))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        

    private void jTextFieldInTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInTempActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        // TODO add your handling code here:
        if(exc.apenasTexto(jTextFieldInTime.getText())&&exc.apenasTexto(jTextFieldInTemp.getText()))
            JOptionPane.showMessageDialog(null, "Apenas numeros!");
        else{
        
            cozinha.setTemperature((short) Integer.parseInt(jTextFieldInTemp.getText()));
            cozinha.setTime((short) Integer.parseInt(jTextFieldInTime.getText()));
                if (cozinha.alarme(cozinha.getTemperature(), cozinha.getTime()) == false){
                    jTextFieldOutTemp.setText(Integer.toString(cozinha.getTemperature()));
                    jTextFieldOutTime.setText(Integer.toString(cozinha.getTime()));

                }else {
                    new TelaAlarme().setVisible(true);
                }
        }
    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZeroActionPerformed
        // TODO add your handling code here:
        cozinha.setTemperature((short) 0);
        cozinha.setTime((short) 0);
        jTextFieldOutTemp.setText(Integer.toString(cozinha.getTemperature()));
        jTextFieldOutTime.setText(Integer.toString(cozinha.getTime()));
        
    }//GEN-LAST:event_jButtonZeroActionPerformed

    private void jTextFieldOutTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOutTimeActionPerformed
        // TODO add your handling code here:
        jTextFieldOutTime.setText(Integer.toString(cozinha.getTime()));
    }//GEN-LAST:event_jTextFieldOutTimeActionPerformed

    private void jTextFieldOutTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOutTempActionPerformed
        // TODO add your handling code here:
        jTextFieldOutTemp.setText(Integer.toString(cozinha.getTemperature()));
    }//GEN-LAST:event_jTextFieldOutTempActionPerformed

    private void jTextFieldInTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonZero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldInTemp;
    private javax.swing.JTextField jTextFieldInTime;
    private javax.swing.JTextField jTextFieldOutTemp;
    private javax.swing.JTextField jTextFieldOutTime;
    // End of variables declaration//GEN-END:variables
}
