package GUI;


import javax.swing.JOptionPane;
import codes.House;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lennon
 */
public class TelaPrincipal extends javax.swing.JFrame {
    codes.House house = new codes.House();
    String out = ""; 

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSala = new javax.swing.JButton();
        jButtonCozinha = new javax.swing.JButton();
        jButtonQuarto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonAlarme = new javax.swing.JButton();
        jButtonEnergia = new javax.swing.JButton();
        jButtonPortao = new javax.swing.JButton();
        jButtonJanelas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CASA IOT");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jButtonSala.setText("SALA");
        jButtonSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalaActionPerformed(evt);
            }
        });

        jButtonCozinha.setText("COZINHA");
        jButtonCozinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCozinhaActionPerformed(evt);
            }
        });

        jButtonQuarto.setText("QUARTO");
        jButtonQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuartoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCozinha, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jButtonQuarto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSala, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCozinha, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/casa.png"))); // NOI18N

        jButtonAlarme.setText("ALARME");
        jButtonAlarme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlarmeActionPerformed(evt);
            }
        });

        jButtonEnergia.setText("ENERGIA");
        jButtonEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnergiaActionPerformed(evt);
            }
        });

        jButtonPortao.setText("PORTAO");
        jButtonPortao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPortaoActionPerformed(evt);
            }
        });

        jButtonJanelas.setText("JANELAS");
        jButtonJanelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJanelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAlarme)
                    .addComponent(jButtonEnergia)
                    .addComponent(jButtonPortao)
                    .addComponent(jButtonJanelas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAlarme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEnergia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPortao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonJanelas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCozinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCozinhaActionPerformed
        // TODO add your handling code here:
        TelaCozinha cozinha = new TelaCozinha();
        cozinha.setVisible(true);
    }//GEN-LAST:event_jButtonCozinhaActionPerformed

    private void jButtonQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuartoActionPerformed
        // TODO add your handling code here:
       TelaQuarto quarto = new TelaQuarto();
       quarto.setVisible(true);
    }//GEN-LAST:event_jButtonQuartoActionPerformed

    private void jButtonSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalaActionPerformed
        // TODO add your handling code here:
        TelaSala sala = new TelaSala();
        sala.setVisible(true);
    }//GEN-LAST:event_jButtonSalaActionPerformed

    private void jButtonEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnergiaActionPerformed
        // TODO add your handling code here:
        
        house.setEnergy(house.getEnergy());
        if (house.getEnergy() == true) out = "ativada";
        else if (house.getEnergy() == false ){
            out = "desativada";
            house.setAlarm(true);
            house.setWindowsAll(true);
        }
        
        JOptionPane.showMessageDialog(null, "A energia geral foi "+out);
    }//GEN-LAST:event_jButtonEnergiaActionPerformed

    private void jButtonAlarmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlarmeActionPerformed
        // TODO add your handling code here:
        
        if (house.getEnergy() == true){
            house.setAlarm(house.getAlarm());
            if (house.getAlarm() == true) out = "ativado";
            else if (house.getAlarm() == false ) out = "desativado";
        
            JOptionPane.showMessageDialog(null, "O alarme foi "+out);
        } else { 
            JOptionPane.showMessageDialog(null, "A energia deve ser ativada!");
        }
        
        
    }//GEN-LAST:event_jButtonAlarmeActionPerformed

    private void jButtonPortaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPortaoActionPerformed
        // TODO add your handling code here:
        
        if (house.getEnergy() == true){
            house.setGate(house.getGate());
            if (house.getGate() == true) out = "Fechado";
            else if (house.getGate() == false ) out = "Aberto";
        
            JOptionPane.showMessageDialog(null, "O portao foi "+out);
        }else { 
            JOptionPane.showMessageDialog(null, "A energia deve ser ativada!");
        }
    }//GEN-LAST:event_jButtonPortaoActionPerformed

    private void jButtonJanelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJanelasActionPerformed
        // TODO add your handling code here:
            
        
        if(house.getEnergy() == true){
            house.setWindowsAll(house.getWindowsAll());
            if (house.getWindowsAll() == true) out = "Fechadas e lacradas";
            else if (house.getWindowsAll() == false ) out = "Abertas";
        
            JOptionPane.showMessageDialog(null, "As janelas foram "+out);
        } else {
            JOptionPane.showMessageDialog(null, "A energia deve ser ativada");
        }
        
    }//GEN-LAST:event_jButtonJanelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
          JOptionPane.showMessageDialog(null, "Bem-vindo ao software que controla a sua casa!"); 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlarme;
    private javax.swing.JButton jButtonCozinha;
    private javax.swing.JButton jButtonEnergia;
    private javax.swing.JButton jButtonJanelas;
    private javax.swing.JButton jButtonPortao;
    private javax.swing.JButton jButtonQuarto;
    private javax.swing.JButton jButtonSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
