package GUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import codes.Dormitory;
import javax.swing.JOptionPane;

/**
 *
 * @author lennon
 */
public class TelaQuarto extends javax.swing.JFrame {
    Dormitory quarto = new Dormitory();
    String out = "";
    /**
     * Creates new form TelaQuarto
     */
    public TelaQuarto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonLuz = new javax.swing.JButton();
        jButtonAr = new javax.swing.JButton();
        jButtonJanela = new javax.swing.JButton();
        jButtonTV = new javax.swing.JButton();
        quartin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("QUARTO");
        setResizable(false);

        jButtonLuz.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLuz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/luz.png"))); // NOI18N
        jButtonLuz.setText("LUZ");
        jButtonLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLuzActionPerformed(evt);
            }
        });

        jButtonAr.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/central.png"))); // NOI18N
        jButtonAr.setText("CENTRAL DE AR");
        jButtonAr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArActionPerformed(evt);
            }
        });

        jButtonJanela.setBackground(new java.awt.Color(255, 255, 255));
        jButtonJanela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/janela.png"))); // NOI18N
        jButtonJanela.setText("JANELA");
        jButtonJanela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJanelaActionPerformed(evt);
            }
        });

        jButtonTV.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tv.png"))); // NOI18N
        jButtonTV.setText("TV");
        jButtonTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTVActionPerformed(evt);
            }
        });

        quartin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/quartor.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLuz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonJanela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(quartin)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quartin, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonLuz, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonJanela, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTV, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJanelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJanelaActionPerformed
        // TODO add your handling code here:
         quarto.setWindows(quarto.mudaJanela(quarto.getWindows()));
        out = "fechada";
        if (quarto.getWindows() == true ) 
            out = "aberta";
        
        JOptionPane.showMessageDialog(null, "A janela foi "+ out);
    }//GEN-LAST:event_jButtonJanelaActionPerformed

    private void jButtonArActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArActionPerformed
        // TODO add your handling code here:
        new CentralAr().setVisible(true);
    }//GEN-LAST:event_jButtonArActionPerformed

    private void jButtonTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTVActionPerformed
        // TODO add your handling code here:
        new TV().setVisible(true);
    }//GEN-LAST:event_jButtonTVActionPerformed

    private void jButtonLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLuzActionPerformed
        // TODO add your handling code here:
        quarto.setLight(quarto.mudaLuz(quarto.getLight()));
        out = "desligada";
        if(quarto.getLight() == true) out = "ligada";
        
        JOptionPane.showMessageDialog(null, "A luz foi "+this.out);
    }//GEN-LAST:event_jButtonLuzActionPerformed

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAr;
    private javax.swing.JButton jButtonJanela;
    private javax.swing.JButton jButtonLuz;
    private javax.swing.JButton jButtonTV;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel quartin;
    // End of variables declaration//GEN-END:variables
}
